@dominio = localhost
@port = 3000
@protocol = http
@url = {{protocol}}://{{dominio}}:{{port}}
###
GET {{url}}/api/Cotizacion/ObtenerTodosServicios

###
get  {{url}}/api/reserva/DataReserva/CRUDReservaCotizacion

###
get  {{url}}/api/v2/reservaCotizacion?estado=0

###
post  {{url}}/api/v2/reservaCotizacion
Content-Type: application/json

{
  "reservaCotizacion" :{
    "asd":"asd"
  }
}