### Main Variables
###
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json


### Listar pasajeros por reserva
GET http://{{host}}/api/reserva/Voucher/GetVocher/RC00017