/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Wo0znuQ6D",
    "aws_user_pools_web_client_id": "mhhjaudnbts6cae4gi7d86p3f",
    "oauth": {}
};


export default awsmobile;
